wallpaper {
    monitor = eDP-1
    path = /home/player01/Pictures/wallpapers/1peakpxbugger.jpg
    fit_mode = cover
}
wallpaper {
    monitor = HDMI-A-1
    path = /home/player01/Pictures/wallpapers/1peakpxbugger.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = /home/player01/Pictures/wallpapers/1peakpxbugger.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-2
    path = /home/player01/Pictures/wallpapers/1peakpxbugger.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-3
    path = /home/player01/Pictures/wallpapers/1peakpxbugger.jpg
    fit_mode = cover
}
