hl.on("hyprland.start", function ()
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("waybar")
	hl.exec_cmd("pipewire")
	hl.exec_cmd("pipewire-pulse")
	hl.exec_cmd("wireplumber")
	hl.exec_cmd("dbus-update-activation-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("dbus-update-activation-environment --all")
end)

hl.on("hyprland.shutdown", function ()
	hl.exec_cmd("killall waybar")
	hl.exec_cmd("killall wireplumber")
	hl.exec_cmd("killall pipewire-pulse")
	hl.exec_cmd("killall pipewire")
end)
