live_config_reload = true

[colors.bright]
blue = "#80a0ff"
cyan = "#00ffff"
green = "#62fd62"
magenta = "#ff80ff"
red = "#ffa0a0"
yellow = "#ffff00"

[colors.cursor]
cursor = "#EDEDED"
text = "#1E1E2E"

[colors.dim]
blue = "#80a0ff"
cyan = "#00ffff"
green = "#62fd62"
magenta = "#ff80ff"
red = "#ffa0a0"
yellow = "#ffff00"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#62fd62"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#80a0ff"
cyan = "#00ffff"
green = "#62fd62"
magenta = "#ff80ff"
red = "#ffa0a0"
white = "#BAC2DE"
yellow = "#ffff00"

[colors.primary]
background = "#090110"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#BABABA"
text = "#1E1E2E"

[cursor]
blink_interval = 440
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 17

[font.normal]
family = "jetbrains mono"

[font.offset]
x = 0
y = -1

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
opacity = 0.79

[window.padding]
x = 8
y = 5
